[2024-07-10T08:48:16.665+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T08:48:16.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.get_business_date manual__2024-07-10T08:47:46.733460+00:00 [queued]>
[2024-07-10T08:48:16.715+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.get_business_date manual__2024-07-10T08:47:46.733460+00:00 [queued]>
[2024-07-10T08:48:16.716+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-10T08:48:16.758+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): get_business_date> on 2024-07-10 08:47:46.733460+00:00
[2024-07-10T08:48:16.791+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2748) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-10T08:48:16.795+0000] {standard_task_runner.py:63} INFO - Started process 2763 to run task
[2024-07-10T08:48:16.798+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'get_business_date', 'manual__2024-07-10T08:47:46.733460+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpu28uuqk8']
[2024-07-10T08:48:16.809+0000] {standard_task_runner.py:91} INFO - Job 238: Subtask get_business_date
[2024-07-10T08:48:16.946+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.get_business_date manual__2024-07-10T08:47:46.733460+00:00 [running]> on host 72ddc95a1902
[2024-07-10T08:48:17.317+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='get_business_date' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T08:47:46.733460+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-10T08:47:46.733460+00:00'
[2024-07-10T08:48:17.319+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T08:48:17.320+0000] {python.py:237} INFO - Done. Returned value was: 2024-07-09 00:00:00
[2024-07-10T08:48:17.322+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T08:48:17.364+0000] {xcom.py:675} ERROR - Object of type Timestamp is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2024-07-10T08:48:17.366+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas._libs.tslibs.timestamps.Timestamp'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Timestamp is not JSON serializable
[2024-07-10T08:48:17.409+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=market_etl, task_id=get_business_date, run_id=manual__2024-07-10T08:47:46.733460+00:00, execution_date=20240710T084746, start_date=20240710T084816, end_date=20240710T084817
[2024-07-10T08:48:17.464+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 238 for task get_business_date (Object of type Timestamp is not JSON serializable; 2763)
[2024-07-10T08:48:17.518+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-10T08:48:17.558+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T08:48:17.560+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
