[2024-07-01T05:26:42.680+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T05:26:42.695+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.upload_to_s3 manual__2024-07-01T05:26:17.664409+00:00 [queued]>
[2024-07-01T05:26:42.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.upload_to_s3 manual__2024-07-01T05:26:17.664409+00:00 [queued]>
[2024-07-01T05:26:42.703+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-01T05:26:42.711+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): upload_to_s3> on 2024-07-01 05:26:17.664409+00:00
[2024-07-01T05:26:42.718+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-01T05:26:42.719+0000] {standard_task_runner.py:63} INFO - Started process 75 to run task
[2024-07-01T05:26:42.720+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'upload_to_s3', 'manual__2024-07-01T05:26:17.664409+00:00', '--job-id', '359', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp3hjn_9i_']
[2024-07-01T05:26:42.722+0000] {standard_task_runner.py:91} INFO - Job 359: Subtask upload_to_s3
[2024-07-01T05:26:42.784+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.upload_to_s3 manual__2024-07-01T05:26:17.664409+00:00 [running]> on host 5eec0a067191
[2024-07-01T05:26:42.915+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T05:26:17.664409+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-01T05:26:17.664409+00:00'
[2024-07-01T05:26:42.916+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T05:26:42.931+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2024-07-01T05:26:42.932+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-07-01T05:26:42.932+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2024-07-01T05:26:45.014+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-01T05:26:45.016+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-01T05:26:45.050+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=upload_to_s3, run_id=manual__2024-07-01T05:26:17.664409+00:00, execution_date=20240701T052617, start_date=20240701T052642, end_date=20240701T052645
[2024-07-01T05:26:45.115+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-01T05:26:45.139+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-01T05:26:45.142+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
