[2024-07-09T08:44:03.618+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T08:44:03.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_etl.load_data_to_postgres scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-09T08:44:03.641+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_etl.load_data_to_postgres scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-09T08:44:03.642+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-07-09T08:44:03.650+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data_to_postgres> on 2024-07-01 00:00:00+00:00
[2024-07-09T08:44:03.661+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=614) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-09T08:44:03.667+0000] {standard_task_runner.py:63} INFO - Started process 616 to run task
[2024-07-09T08:44:03.668+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'market_etl', 'load_data_to_postgres', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpgwv5yd3t']
[2024-07-09T08:44:03.675+0000] {standard_task_runner.py:91} INFO - Job 151: Subtask load_data_to_postgres
[2024-07-09T08:44:03.740+0000] {task_command.py:426} INFO - Running <TaskInstance: market_etl.load_data_to_postgres scheduled__2024-07-01T00:00:00+00:00 [running]> on host 7aa01bd35230
[2024-07-09T08:44:03.967+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='market_etl' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-09T08:44:03.968+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T08:44:03.977+0000] {base.py:84} INFO - Using connection ID 'market_database_conn' for task execution.
[2024-07-09T08:44:04.088+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-09T08:44:04.089+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T08:44:04.100+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_etl, task_id=load_data_to_postgres, run_id=scheduled__2024-07-01T00:00:00+00:00, execution_date=20240701T000000, start_date=20240709T084403, end_date=20240709T084404
[2024-07-09T08:44:04.140+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-09T08:44:04.159+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T08:44:04.160+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
